env:
  node: true
  es2015: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 12
  sourceType: module
  
rules: 
  no-console: 0
  import/extensions: 0

  linebreak-style: ["error", "windows"]